# Generated by Django 5.1.4 on 2025-02-14 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_chatmessage_audio_chatmessage_file_chatmessage_image_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="voice_message",
            field=models.FileField(
                blank=True, null=True, upload_to="chat_media/voice/"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="voice_message",
            field=models.FileField(
                blank=True, null=True, upload_to="message_media/voice/"
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="audio",
            field=models.FileField(
                blank=True, null=True, upload_to="chat_media/audio/"
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="chat_media/files/"
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="chat_media/images/"
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="thread",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_messages",
                to="chat.thread",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="audio",
            field=models.FileField(
                blank=True, null=True, upload_to="message_media/audio/"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="message_media/files/"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="message_media/images/"
            ),
        ),
        migrations.AlterField(
            model_name="thread",
            name="first_person",
            field=models.ForeignKey(
                default=20,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thread_first_person",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="thread",
            name="second_person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thread_second_person",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
